15 react router
rmcguinness/WoodstockCodeCamp pull request #33
Opened 2023-05-09 02:33 UTC by CBlack86

Added router to the main.jsx file

2023-05-09 03:41 UTC, rmcguinness requested changes

2023-05-09 03:41 UTC, rmcguinness commented on src/App.jsx
Prior to this, please review the comments on main.tsx

When complete, the App should return a Router, please see the following example:

https://github.com/remix-run/react-router/blob/dev/examples/basic/src/App.tsx

2023-05-09 03:41 UTC, rmcguinness commented on src/main.jsx
Since this is a react app, it's best to stick with React native structures and stay away from raw JavaScript when possible. To help understand, the current code would paint the screen, then execute the javascript at the end.

Please look at the following example, then go back and work on the App and Layout

https://github.com/remix-run/react-router/blob/dev/examples/basic/src/main.tsx

2023-05-10 02:03 UTC, CBlack86 commented on src/App.jsx
I added the Routes and Route to App.jsx similar to the example above

2023-05-10 02:03 UTC, CBlack86 commented on src/main.jsx
I wrapped the <App /> inside BrowserRouter similar to the example you provided

2023-05-10 12:21 UTC, rmcguinness submitted a review, later dismissed
Great work, does this feel more natural?

2023-05-10 12:33 UTC, rmcguinness requested changes

2023-05-10 12:33 UTC, rmcguinness commented on src/App.jsx
In order for this to work, you'll need to add the template where route / => template.
And the template MUST have an <Outlet /> in order to draw the page.

2023-05-10 18:13 UTC, rmcguinness commented
Awesome work, the merge is not complete to may2023 and the branch was verified.

2023-05-10 18:13 UTC, closed without merging